extends SceneTree
const P=preload("res://scripts/puzzle_engine.gd")
const Session=preload("res://scripts/session_store.gd")
const Model=preload("res://scripts/cafe_model.gd")
var checks=0
func check(value: bool,label: String) -> void:
	checks+=1
	if not value: push_error(label);quit(1)
func _initialize() -> void:
	ProjectSettings.set_setting("lumi/review_mode",true)
	call_deferred("run")
func run() -> void:
	check(str(ProjectSettings.get_setting("application/config/name")).begins_with("Lumi-Isolated-"),"Refuse production storage")
	for seed in [1,2,9,100,2147483647]:
		var engine=P.new();engine.initialize(0,seed)
		check(engine.moves==18 and engine.need_fruit[1]==3,"Review target and moves")
		check(engine.find_runs().is_empty() and engine.phase=="idle","No automatic opening clear")
		var pair=engine.hint()
		check(pair==[Vector2i(3,0),Vector2i(3,1)],"Deterministic first goal match")
		var result=engine.try_swap(pair[0],pair[1])
		check(result.accepted and engine.phase=="win" and engine.moves==17 and engine.got_fruit[1]>=3,"One normal swap wins review")
	var model=Model.new();var session=Session.new();session.load_state()
	var engine=P.new();engine.initialize(0,90)
	check(model.begin_attempt(1,"review-native-attempt-a").ok,"Attempt starts normally")
	check(session.begin_puzzle("review-native-attempt-a",engine,true).ok,"Review checkpoint schema accepted")
	var restored=P.new();var saved=Session.new();saved.load_state()
	check(saved.restore_engine(restored) and restored.board==engine.board and restored.moves==18,"Exact easy review resume")
	var pair=restored.hint();restored.try_swap(pair[0],pair[1])
	check(saved.begin_completion(restored).ok,"Pending completion checkpoint valid")
	check(model.finish_attempt("review-native-attempt-a",true).ok and model.read().balance==100,"Normal first reward100")
	model.finish_attempt("review-native-attempt-a",true)
	check(model.read().balance==100,"Duplicate reward suppressed")
	check(saved.acknowledge_completion().ok and not saved.should_first_puzzle(),"First completion opens cafe")
	engine=P.new();engine.initialize(0,15)
	model.begin_attempt(1,"review-native-attempt-b");session=Session.new();session.load_state()
	check(session.begin_puzzle("review-native-attempt-b",engine,false).ok,"Cafe replay persists normally")
	pair=engine.hint();engine.try_swap(pair[0],pair[1]);session.begin_completion(engine)
	model.finish_attempt("review-native-attempt-b",true)
	check(model.read().balance==135,"Normal repeat reward35")
	ProjectSettings.set_setting("lumi/review_mode",false)
	var normal=P.new();normal.initialize(0,90)
	check(normal.need_fruit[1]==12 and normal.levels.size()==8,"All normal levels preserved")
	print("REVIEW MODE: ",checks," checks, 0 failures; one normal swap, resume, first100/repeat35")
	quit(0)
