'use strict';
(function(root){
  const KEY='cats-and-coffee-v2',OLD='cats-and-coffee-cafe-v1';
  function makeModel(storage,catalog){
    const ids=new Set(catalog.facilities.map(f=>f.id)),byId=id=>catalog.facilities.find(f=>f.id===id),decorById=id=>(catalog.decorations||[]).find(d=>d.id===id);
    const fail=(reason,message)=>({ok:false,reason,message});
    function fresh(){return {version:2,revision:0,balance:0,openingBalance:0,chapter:1,project:'f05',companion:'cat19',owned:{f19:{level:1,position:{x:48,y:19}}},claimedLevels:[],attempts:{},ledger:[],settings:{reduceMotion:false,lighting:'day',sound:true,effects:'full'},memories:[],order:null,orderBook:{},visits:{},companionRecords:{},decorOwned:{},surfaces:{floor:null,path:null},migration:null};}
    function validate(s){
      if(!s||s.version!==2||!Number.isSafeInteger(s.revision)||s.revision<0||!Number.isSafeInteger(s.balance)||s.balance<0||!Number.isSafeInteger(s.openingBalance)||s.openingBalance<0||!Number.isInteger(s.chapter)||s.chapter<1||s.chapter>6||!Array.isArray(s.ledger)||!Array.isArray(s.claimedLevels)||!Array.isArray(s.memories)||!s.owned||typeof s.owned!=='object'||Array.isArray(s.owned)||!s.attempts||typeof s.attempts!=='object'||Array.isArray(s.attempts)||!s.settings||typeof s.settings.reduceMotion!=='boolean')throw Error('저장 형식이 맞지 않아요. 원본을 보존했습니다.');
      if(s.project!==null&&!ids.has(s.project))throw Error('프로젝트 저장 오류');
      if(typeof s.settings.sound!=='boolean'||!['full','low'].includes(s.settings.effects))throw Error('소리/효과 설정 오류');
      if(!['day','sunset','night'].includes(s.settings.lighting))throw Error('조명 저장 오류');
      if(s.order!==null&&(!s.order||!s.owned[s.order.facility]||!Number.isInteger(s.order.completed)||s.order.completed<0||s.order.completed>2))throw Error('주문 저장 오류');
      if(new Set(s.claimedLevels).size!==s.claimedLevels.length||s.claimedLevels.some(l=>!Number.isInteger(l)||l<1||l>8))throw Error('클리어 기록 저장 오류');
      let total=s.openingBalance;const txids=new Set();
      for(const tx of s.ledger){if(!tx||typeof tx.id!=='string'||txids.has(tx.id)||!Number.isSafeInteger(tx.amount)||!['reward','purchase','upgrade','decoration'].includes(tx.kind))throw Error('거래 기록 저장 오류');txids.add(tx.id);total+=tx.amount;}
      if(total!==s.balance)throw Error('잔액과 거래 기록이 맞지 않아요. 원본을 보존했습니다.');
      if(!s.decorOwned||typeof s.decorOwned!=='object'||Array.isArray(s.decorOwned)||!s.surfaces||Array.isArray(s.surfaces)||!s.orderBook||Array.isArray(s.orderBook)||!s.visits||Array.isArray(s.visits))throw Error('꾸미기/주문 저장 오류');
      for(const [id,o] of Object.entries(s.decorOwned)){if(!decorById(id)||!o||(['floor','path'].includes(decorById(id).kind)&&o.position!==null)||(o.position!==null&&!validPosition(o.position)))throw Error('꾸미기 위치 오류');}
      for(const kind of ['floor','path']){const id=s.surfaces[kind];if(id!==null&&(!s.decorOwned[id]||decorById(id)?.kind!==kind))throw Error('바닥/길 선택 오류');}
      for(const [id,o] of Object.entries(s.orderBook)){if(!s.owned[id]||!o||!Number.isInteger(o.completed)||o.completed<0||o.completed>2||typeof o.served!=='boolean')throw Error('주문 진행 오류');}
      if(!s.companionRecords||Array.isArray(s.companionRecords))throw Error('동행 기록 오류');for(const [id,r]of Object.entries(s.companionRecords)){if(!Object.keys(s.owned).some(key=>byId(key).catId===id)||!r||!Number.isInteger(r.runs)||!Number.isInteger(r.wins)||r.wins<0||r.runs<r.wins||!Number.isInteger(r.lastLevel)||r.lastLevel<1||r.lastLevel>8)throw Error('동행 기록 오류');}
      for(const [id,n] of Object.entries(s.visits)){if(!s.owned[id]||!Number.isInteger(n)||n<0)throw Error('방문 기록 오류');}
      const positions=[];
      for(const [id,item] of Object.entries(s.owned)){
        if(!ids.has(id)||!item||!Number.isInteger(item.level)||item.level<1||item.level>3)throw Error('시설 저장 오류');
        if(item.actionStage!==undefined&&(!Number.isInteger(item.actionStage)||item.actionStage<1||item.actionStage>item.level))throw Error('행동 선택 오류');
        if(item.position!==null){if(!validPosition(item.position))throw Error('배치 저장 오류');positions.push(item.position);}
      }
      for(let i=0;i<positions.length;i++)for(let j=i+1;j<positions.length;j++)if(collides(positions[i],positions[j]))throw Error('시설이 겹쳐 있어요. 저장을 보존했습니다.');
      if(!Object.keys(s.owned).some(id=>byId(id).catId===s.companion))throw Error('동행 고양이 저장 오류');
      for(const [id,a] of Object.entries(s.attempts)){if(!id||!a||!Number.isInteger(a.level)||a.level<1||a.level>8||!['active','won','lost','abandoned'].includes(a.status))throw Error('퍼즐 기록 저장 오류');}
      for(const m of s.memories){if(!m||typeof m.id!=='string'||! /^[A-Za-z0-9:-]{1,128}$/.test(m.id)||!['arrival','growth','story','visit','photo','companion'].includes(m.kind))throw Error('추억 저장 오류');if(m.kind==='photo'){if(!m.layout||Array.isArray(m.layout)||(m.decor&&Array.isArray(m.decor))||!['day','sunset','night'].includes(m.lighting))throw Error('정원 기억 오류');for(const [id,o] of Object.entries(m.layout)){if(!ids.has(id)||!o||!Number.isInteger(o.level)||o.level<1||o.level>3||(o.actionStage!==undefined&&(!Number.isInteger(o.actionStage)||o.actionStage<1||o.actionStage>o.level))||(o.position!==null&&!validPosition(o.position)))throw Error('정원 기억 배치 오류');}for(const [id,o] of Object.entries(m.decor||{})){if(!decorById(id)||!o||(o.position!==null&&!validPosition(o.position)))throw Error('소품 기억 오류');}for(const kind of ['floor','path']){const id=m.surfaces?.[kind];if(id!==undefined&&id!==null&&(!(m.decor||{})[id]||decorById(id)?.kind!==kind))throw Error('기억 바닥/길 오류');}}else if(!s.owned[m.facility])throw Error('추억 시설 오류');}
      const decorPositions=Object.values(s.decorOwned).filter(o=>o.position!==null).map(o=>o.position);for(let i=0;i<decorPositions.length;i++){if(positions.some(p=>decCollides(p,decorPositions[i],8)))throw Error('소품과 시설 위치가 겹쳐요');for(let j=i+1;j<decorPositions.length;j++)if(decCollides(decorPositions[i],decorPositions[j],4))throw Error('소품 위치가 겹쳐요');}
      return s;
    }
    const validPosition=p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x>=8&&p.x<=92&&p.y>=12&&p.y<=87;
    const collides=(a,b)=>Math.hypot((a.x-b.x)/1.3,a.y-b.y)<12;
    const decCollides=(a,b,r)=>Math.hypot((a.x-b.x)/1.3,a.y-b.y)<r;
    function normalize(s){if(s?.version===2){s.settings.sound??=true;s.settings.effects??='full';s.decorOwned??={};s.surfaces??={floor:null,path:null};s.orderBook??={};s.visits??={};s.companionRecords??={};if(s.order){s.order.served??=false;s.orderBook[s.order.facility]??={completed:s.order.completed,served:s.order.served};}}return s;}
    function read(){
      const raw=storage.getItem(KEY);if(raw)return validate(normalize(JSON.parse(raw)));
      const s=fresh(),oldRaw=storage.getItem(OLD);
      if(oldRaw){const old=JSON.parse(oldRaw);if(old.version!==1||!Number.isSafeInteger(old.balance)||old.balance<0||!Array.isArray(old.owned)||!Array.isArray(old.claimed)||!Array.isArray(old.slots))throw Error('이전 저장을 읽을 수 없어요. 원본을 보존했습니다.');
        const mapping={drip:'f05',moka:'f06',latte:'f07'};
        for(const id of old.owned){const newId=mapping[id];if(!newId)throw Error('이전 시설 저장 오류');const idx=old.slots.indexOf(id);s.owned[newId]={level:1,position:idx<0?null:{x:20+(idx%3)*29,y:48+Math.floor(idx/3)*25}};s.chapter=Math.max(s.chapter,byId(newId).chapter);}
        s.balance=old.balance;s.openingBalance=old.balance;s.claimedLevels=[...old.claimed];s.migration='v1';validate(s);
      }
      return s;
    }
    function transact(fn){const s=read(),result=fn(s);if(result.ok&&result.changed){s.revision++;validate(s);const previous=storage.getItem(KEY);if(previous!==null)storage.setItem(KEY+':backup',previous);storage.setItem(KEY,JSON.stringify(s));}return {...result,state:s};}
    function addTx(s,tx){s.balance+=tx.amount;s.ledger.push(tx);}
    function unlock(s){while(s.chapter<6&&s.owned[catalog.chapters[s.chapter-1].representative])s.chapter++;}
    function beginAttempt(level,id){if(!Number.isInteger(level)||level<1||level>8||typeof id!=='string'||id.length<8)return fail('attempt','퍼즐 기록을 시작할 수 없어요.');return transact(s=>{if(s.attempts[id])return fail('duplicate','이미 시작한 퍼즐이에요.');s.attempts[id]={level,status:'active',companion:s.companion};return {ok:true,changed:true,id};});}
    function finishAttempt(id,won){return transact(s=>{const a=s.attempts[id];if(!a)return fail('attempt','퍼즐 기록이 없어요.');if(a.status!=='active')return {ok:true,changed:false,reason:'already_finished',amount:0};a.status=won?'won':'lost';const companion=a.companion||s.companion,record=s.companionRecords[companion]||{runs:0,wins:0,lastLevel:a.level};record.runs++;record.lastLevel=a.level;if(won)record.wins++;s.companionRecords[companion]=record;if(won&&!s.memories.some(m=>m.id==='companion:'+companion)){const facility=Object.keys(s.owned).find(id=>byId(id).catId===companion);s.memories.push({id:'companion:'+companion,kind:'companion',facility});}let amount=0;if(won){amount=s.claimedLevels.includes(a.level)?catalog.rewardRepeat:catalog.rewardFirst;if(!s.claimedLevels.includes(a.level))s.claimedLevels.push(a.level);addTx(s,{id:'reward:'+id,kind:'reward',amount,level:a.level});if(s.order&&s.order.completed<2){s.order.completed++;s.orderBook[s.order.facility]={completed:s.order.completed,served:false};if(s.order.completed===2)s.memories.push({id:'story:'+s.order.facility,kind:'story',facility:s.order.facility});}}return {ok:true,changed:true,amount};});}
    function abandon(id){return transact(s=>{if(!s.attempts[id]||s.attempts[id].status!=='active')return {ok:true,changed:false};s.attempts[id].status='abandoned';return {ok:true,changed:true};});}
    function purchase(id){return transact(s=>{const f=byId(id);if(!f)return fail('facility','시설을 찾을 수 없어요.');if(s.owned[id])return {ok:true,changed:false,reason:'owned'};if(f.chapter>s.chapter)return fail('locked','앞 장의 대표 프로젝트를 먼저 완성해 주세요.');if(s.balance<f.price)return fail('insufficient','커피 방울이 부족해요. 익숙한 퍼즐도 다시 플레이할 수 있어요.');addTx(s,{id:'buy:'+id,kind:'purchase',amount:-f.price,facility:id});s.owned[id]={level:1,position:null};s.memories.push({id:'arrival:'+id,kind:'arrival',facility:id});unlock(s);const gifts={f05:'d-coaster',f13:'d-books',f07:'d-cups',f26:'d-plant',f22:'d-cushion',f31:'d-garden-lamp'},gift=gifts[id];let giftAdded=null;if(gift&&!s.decorOwned[gift]){s.decorOwned[gift]={position:null};giftAdded=gift;}return {ok:true,changed:true,gift:giftAdded};});}
    function upgrade(id){return transact(s=>{const f=byId(id),o=s.owned[id];if(!f||!o)return fail('owned','먼저 시설을 열어주세요.');if(o.level===3)return {ok:true,changed:false,reason:'max'};const cost=f.upgrades[o.level-1];if(s.balance<cost)return fail('insufficient','커피 방울이 부족해요.');addTx(s,{id:'upgrade:'+id+':'+(o.level+1),kind:'upgrade',amount:-cost,facility:id});o.level++;s.memories.push({id:'growth:'+id+':'+o.level,kind:'growth',facility:id});return {ok:true,changed:true};});}
    function setProject(id){return transact(s=>{if(id!==null&&!ids.has(id))return fail('facility','알 수 없는 목표예요.');s.project=id;return {ok:true,changed:true};});}
    function setCompanion(id){return transact(s=>{if(!Object.keys(s.owned).some(f=>byId(f).catId===id))return fail('owned','입주한 고양이를 골라주세요.');s.companion=id;return {ok:true,changed:true};});}
    function saveLayout(layout,expectedRevision,decorLayout=null){return transact(s=>{if(s.revision!==expectedRevision)return fail('conflict','다른 저장이 변경됐어요. 편집을 다시 열어주세요.');if(!layout||Object.keys(layout).length!==Object.keys(s.owned).length||Object.keys(layout).some(id=>!s.owned[id]))return fail('layout','배치 목록이 맞지 않아요.');const placed=[];for(const p of Object.values(layout)){if(p!==null){if(!validPosition(p))return fail('bounds','시설을 정원 안쪽에 놓아주세요.');if(placed.some(x=>collides(x,p)))return fail('overlap','시설 사이에 조금 더 여백을 주세요.');placed.push(p);}}const decorations=decorLayout||Object.fromEntries(Object.entries(s.decorOwned).map(([id,o])=>[id,o.position]));if(Object.keys(decorations).length!==Object.keys(s.decorOwned).length||Object.keys(decorations).some(id=>!s.decorOwned[id]))return fail('layout','소품 목록이 변경되었어요.');const dp=[];for(const [id,p] of Object.entries(decorations)){if(p!==null){if(!validPosition(p))return fail('bounds','소품을 정원 안에 놓아주세요.');if(placed.some(x=>decCollides(x,p,8))||dp.some(x=>decCollides(x,p,4)))return fail('overlap','소품 사이에 공간을 남겨주세요.');dp.push(p);}}for(const [id,p]of Object.entries(layout))s.owned[id].position=p;for(const [id,p]of Object.entries(decorations))s.decorOwned[id].position=p;return {ok:true,changed:true};});}
    function setting(value){return transact(s=>{s.settings.reduceMotion=!!value;return {ok:true,changed:true};});}
    function sound(value){return transact(s=>{s.settings.sound=!!value;return {ok:true,changed:true};});}
    function effects(value){return transact(s=>{if(!['full','low'].includes(value))return fail('effects','알 수 없는 효과 설정이에요.');s.settings.effects=value;return {ok:true,changed:true};});}
    function lighting(value){return transact(s=>{if(!['day','sunset','night'].includes(value))return fail('lighting','알 수 없는 조명이에요.');s.settings.lighting=value;return {ok:true,changed:true};});}
    function beginOrder(id){return transact(s=>{if(!s.owned[id])return fail('owned','소유한 시설을 선택해주세요.');if(s.order?.facility===id)return {ok:true,changed:false,reason:s.order.completed===2?'complete':'active'};const progress=s.orderBook[id]||{completed:s.memories.some(m=>m.id==='story:'+id)?2:0,served:false};s.order={facility:id,...progress};s.orderBook[id]={...progress};return {ok:true,changed:true,reason:progress.completed===2?'complete':'active'};});}
    function serveOrder(){return transact(s=>{const o=s.order;if(!o||o.completed<2)return fail('not_ready','퍼즐 두 판을 마쳐 주문을 준비해주세요.');if(o.served)return {ok:true,changed:false,reason:'served'};if(!s.owned[o.facility].position)return fail('stored','시설을 정원에 배치하면 손님을 맞이할 수 있어요.');o.served=true;s.orderBook[o.facility]={completed:2,served:true};s.visits[o.facility]=(s.visits[o.facility]||0)+1;s.memories.push({id:'visit:'+o.facility+':'+s.visits[o.facility],kind:'visit',facility:o.facility});return {ok:true,changed:true};});}
    function purchaseDecoration(id){return transact(s=>{const d=decorById(id);if(!d)return fail('decoration','알 수 없는 소품이에요.');if(s.decorOwned[id])return {ok:true,changed:false,reason:'owned'};if(s.balance<d.price)return fail('insufficient','커피 방울이 부족해요.');addTx(s,{id:'decor:'+id,kind:'decoration',amount:-d.price,decoration:id});s.decorOwned[id]={position:null};return {ok:true,changed:true};});}
    function equipSurface(id){return transact(s=>{const d=decorById(id);if(!d||!s.decorOwned[id]||!['floor','path'].includes(d.kind))return fail('decoration','구매한 바닥 또는 길을 선택해주세요.');s.surfaces[d.kind]=id;return {ok:true,changed:true};});}
    function behavior(id,stage){return transact(s=>{const o=s.owned[id];if(!o||!Number.isInteger(stage)||stage<1||stage>o.level)return fail('stage','해금된 행동을 선택해주세요.');o.actionStage=stage;return {ok:true,changed:true};});}
    function restoreSave(raw){let restored;try{restored=validate(normalize(JSON.parse(raw)));}catch(e){return fail('invalid_save','복원할 저장을 확인할 수 없어요. 현재 자료를 보존했습니다.');}const current=storage.getItem(KEY);if(current!==null)storage.setItem(KEY+':before-restore',current);storage.setItem(KEY,JSON.stringify(restored));return {ok:true,changed:true,state:restored};}
    function restoreBackup(){const raw=storage.getItem(KEY+':backup');return raw===null?fail('no_backup','복원할 이전 저장이 없어요.'):restoreSave(raw);}
    function remember(id){if(typeof id!=='string'||id.length<8||! /^[A-Za-z0-9:-]{1,128}$/.test(id))return fail('id','장면 기록 이름이 필요해요.');return transact(s=>{if(s.memories.some(m=>m.id===id))return {ok:true,changed:false};s.memories.push({id,kind:'photo',decor:JSON.parse(JSON.stringify(s.decorOwned)),surfaces:{...s.surfaces},layout:JSON.parse(JSON.stringify(s.owned)),lighting:s.settings.lighting});return {ok:true,changed:true};});}
    return {key:KEY,read,validate,beginAttempt,finishAttempt,abandon,purchase,upgrade,setProject,setCompanion,saveLayout,setting,sound,effects,lighting,beginOrder,serveOrder,purchaseDecoration,equipSurface,behavior,restoreSave,restoreBackup,remember,byId,decorById};
  }
  if(typeof module==='object'&&module.exports)module.exports={makeModel,KEY,OLD};else root.CafeModel={makeModel,KEY,OLD};
})(globalThis);
