const test=require('node:test'),assert=require('node:assert/strict');
const catalog=require('./cafe-catalog.js'),{makeModel,KEY,OLD}=require('./cafe-model.js');
function storage(initial={}){const m=new Map(Object.entries(initial));return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)};}
function setup(initial){const s=storage(initial),m=makeModel(s,catalog);let n=0;return {s,m,win(level=1){const id='attempt-'+(++n);assert.equal(m.beginAttempt(level,id).ok,true);return m.finishAttempt(id,true);}};}
test('36 facilities, unique dedicated cats, exact design chapter membership',()=>{assert.equal(catalog.facilities.length,36);assert.equal(new Set(catalog.facilities.map(f=>f.catId)).size,36);assert.equal(new Set(catalog.chapters.flatMap(c=>c.facilities)).size,36);assert.deepEqual(catalog.chapters[0].facilities,['f19','f05','f21','f25','f01','f20']);});
test('first and repeat wins pay, same completion cannot pay twice',()=>{const {m,win}=setup();assert.equal(win().amount,100);assert.equal(m.finishAttempt('attempt-1',true).amount,0);assert.equal(win().amount,35);assert.equal(m.read().balance,135);});
test('failure and abandonment have no reward; cannot claim unknown attempt',()=>{const {m}=setup();m.beginAttempt(1,'loss-run-1');assert.equal(m.finishAttempt('loss-run-1',false).amount,0);assert.equal(m.finishAttempt('loss-run-1',true).amount,0);m.beginAttempt(1,'abort-run-1');m.abandon('abort-run-1');assert.equal(m.finishAttempt('abort-run-1',true).amount,0);assert.equal(m.finishAttempt('missing',true).ok,false);assert.equal(m.read().balance,0);});
test('purchase is atomic, insufficient balance and duplicate purchase preserve wallet',()=>{const {m,win}=setup();assert.equal(m.purchase('f05').reason,'insufficient');win();assert.equal(m.purchase('f05').ok,true);assert.equal(m.read().balance,20);assert.equal(m.purchase('f05').changed,false);assert.equal(m.read().balance,20);assert.equal(m.read().chapter,2);assert.equal(m.purchase('f07').reason,'locked');});
test('all 36 facilities and three growth levels reachable with easy replay',()=>{const {m,win}=setup();for(let chapter=1;chapter<=6;chapter++){for(const f of catalog.facilities.filter(x=>x.chapter===chapter)){if(m.read().owned[f.id])continue;while(m.read().balance<f.price)win();assert.equal(m.purchase(f.id).ok,true);}}for(const f of catalog.facilities){while(m.read().owned[f.id].level<3){const cost=f.upgrades[m.read().owned[f.id].level-1];while(m.read().balance<cost)win();assert.equal(m.upgrade(f.id).ok,true);}}assert.equal(Object.keys(m.read().owned).length,36);assert.equal(m.read().chapter,6);assert.ok(Object.values(m.read().owned).every(o=>o.level===3));assert.equal(m.upgrade('f05').changed,false);});
test('layout saves, stores, restores; overlap, bounds and stale edits reject atomically',()=>{const {m,win,s}=setup();win();m.purchase('f05');let state=m.read(),draft={f19:state.owned.f19.position,f05:{x:22,y:45}};assert.equal(m.saveLayout(draft,state.revision).ok,true);state=m.read();const previous=s.getItem(KEY);assert.equal(m.saveLayout({...draft,f05:{...draft.f19}},state.revision).reason,'overlap');assert.equal(s.getItem(KEY),previous);assert.equal(m.saveLayout({...draft,f05:{x:1,y:45}},state.revision).reason,'bounds');assert.equal(m.saveLayout(draft,state.revision-1).reason,'conflict');assert.equal(m.saveLayout({...draft,f05:null},state.revision).ok,true);assert.equal(m.read().owned.f05.position,null);assert.equal(m.read().owned.f05.level,1);});
test('reload, preferences, companion and project survive',()=>{const {m,s,win}=setup();win();m.purchase('f05');m.setProject('f13');m.setCompanion('cat05');m.setting(true);const reload=makeModel(s,catalog).read();assert.equal(reload.project,'f13');assert.equal(reload.companion,'cat05');assert.equal(reload.settings.reduceMotion,true);assert.deepEqual(reload,m.read());});
test('v1 migration preserves old save, balance, ownership and first-clear history',()=>{const old={version:1,balance:60,claimed:[1],owned:['drip'],slots:[null,null,'drip',null,null,null]},raw=JSON.stringify(old);const {m,s,win}=setup({[OLD]:raw});const state=m.read();assert.equal(state.balance,60);assert.ok(state.owned.f05);assert.equal(state.owned.f05.position.x,78);assert.equal(win().amount,35);assert.equal(m.read().balance,95);assert.equal(s.getItem(OLD),raw);});
test('corrupt save remains intact and storage failure cannot spend',()=>{const broken='{',s=storage({[KEY]:broken});assert.throws(()=>makeModel(s,catalog).read());assert.equal(s.getItem(KEY),broken);const normal=setup();normal.win();const before=normal.s.getItem(KEY);normal.s.setItem=()=>{throw Error('quota')};assert.throws(()=>normal.m.purchase('f05'));assert.equal(normal.s.getItem(KEY),before);});
test('facility story advances on two distinct wins, repeat completion does not advance twice',()=>{const {m,win}=setup();m.beginOrder('f19');win();m.finishAttempt('attempt-1',true);assert.equal(m.read().order.completed,1);win();assert.equal(m.read().order.completed,2);assert.equal(m.read().memories.filter(x=>x.kind==='story').length,1);assert.equal(m.beginOrder('f19').reason,'complete');assert.equal(m.read().balance,135);});
test('remembered garden and freely selected lighting survive reload without changing current layout',()=>{const {m,s}=setup();m.lighting('night');const before=JSON.stringify(m.read().owned);m.remember('photo-test-1');m.lighting('sunset');const state=makeModel(s,catalog).read();assert.equal(state.settings.lighting,'sunset');assert.equal(state.memories[0].lighting,'night');assert.equal(JSON.stringify(state.memories[0].layout),before);assert.equal(JSON.stringify(state.owned),before);});
test('reopening active order preserves progress',()=>{const {m,win}=setup();m.beginOrder('f19');win();m.beginOrder('f19');assert.equal(m.read().order.completed,1);});
test('decor purchase is atomic, surfaces and placements persist independently',()=>{const {m,win,s}=setup();assert.equal(m.purchaseDecoration('d-plant').reason,'insufficient');win();assert.equal(m.purchaseDecoration('d-wood-floor').ok,true);assert.equal(m.equipSurface('d-wood-floor').ok,true);assert.equal(m.purchaseDecoration('d-plant').ok,true);const b=m.read().balance;assert.equal(m.purchaseDecoration('d-plant').changed,false);assert.equal(m.read().balance,b);const st=m.read();assert.equal(m.saveLayout({f19:st.owned.f19.position},st.revision,{'d-wood-floor':null,'d-plant':{x:20,y:70}}).ok,true);const r=makeModel(s,catalog).read();assert.equal(r.surfaces.floor,'d-wood-floor');assert.deepEqual(r.decorOwned['d-plant'].position,{x:20,y:70});assert.equal(r.owned.f19.level,1);});
test('decoration collision, bounds and cancel-by-no-write preserve original layout',()=>{const {m,win,s}=setup();win();m.purchaseDecoration('d-plant');const st=m.read(),raw=s.getItem(KEY),layout={f19:st.owned.f19.position};assert.equal(m.saveLayout(layout,st.revision,{'d-plant':st.owned.f19.position}).reason,'overlap');assert.equal(m.saveLayout(layout,st.revision,{'d-plant':{x:0,y:50}}).reason,'bounds');assert.equal(s.getItem(KEY),raw);});
test('facility orders retain independent progress and require placement to serve once',()=>{const {m,win}=setup();win();m.purchase('f05');m.beginOrder('f05');win();m.beginOrder('f19');win();m.beginOrder('f05');assert.equal(m.read().order.completed,1);win();assert.equal(m.serveOrder().reason,'stored');const st=m.read();m.saveLayout({f19:st.owned.f19.position,f05:{x:22,y:45}},st.revision);assert.equal(m.serveOrder().ok,true);assert.equal(m.read().visits.f05,1);assert.equal(m.serveOrder().changed,false);assert.equal(m.read().visits.f05,1);m.beginOrder('f19');assert.equal(m.read().order.completed,1);});
test('prior behavior selection does not reduce growth and persists through storage',()=>{const {m,win,s}=setup();for(let i=0;i<5;i++)win();m.purchase('f05');m.upgrade('f05');assert.equal(m.behavior('f05',1).ok,true);const st=m.read();m.saveLayout({f19:st.owned.f19.position,f05:null},st.revision);assert.equal(makeModel(s,catalog).read().owned.f05.actionStage,1);assert.equal(m.read().owned.f05.level,2);assert.equal(m.behavior('f05',3).reason,'stage');});
test('corrupt save can restore verified backup, invalid import leaves raw untouched',()=>{const {m,win,s}=setup();win();const correct=s.getItem(KEY);m.setting(true);s.setItem(KEY,'{broken');assert.throws(()=>m.read());assert.equal(m.restoreSave('{broken').reason,'invalid_save');assert.equal(s.getItem(KEY),'{broken');assert.equal(m.restoreBackup().ok,true);assert.equal(m.read().balance,100);assert.equal(s.getItem(KEY+':before-restore'),'{broken');const bad=JSON.parse(correct);bad.balance++;const raw=s.getItem(KEY);assert.equal(m.restoreSave(JSON.stringify(bad)).reason,'invalid_save');assert.equal(s.getItem(KEY),raw);});
test('old v2 schemas normalize without overwriting raw; corrupt memories reject',()=>{const {m,win,s}=setup();win();const old=m.read();delete old.decorOwned;delete old.surfaces;delete old.orderBook;delete old.visits;s.setItem(KEY,JSON.stringify(old));const raw=s.getItem(KEY);assert.deepEqual(m.read().decorOwned,{});assert.equal(s.getItem(KEY),raw);old.memories=[{id:'bad',kind:'arrival',facility:'missing'}];assert.equal(m.restoreSave(JSON.stringify(old)).reason,'invalid_save');});
test("companion records use the cat at start, count once and persist",()=>{const {m,win,s}=setup();win();m.purchase("f05");m.beginAttempt(1,"companion-start-1");m.setCompanion("cat05");m.finishAttempt("companion-start-1",true);m.finishAttempt("companion-start-1",true);assert.equal(m.read().companionRecords.cat19.wins,2);assert.equal(m.read().companionRecords.cat05,undefined);win();assert.equal(makeModel(s,catalog).read().companionRecords.cat05.wins,1);assert.equal(m.read().memories.filter(x=>x.id==="companion:cat05").length,1);});

test("corrupted memory fields and unsafe IDs are rejected before import",()=>{const {m,s}=setup();m.remember("photo-safe-1");const st=m.read(),raw=s.getItem(KEY);st.memories[0].id='x" onclick="alert(1)';assert.equal(m.restoreSave(JSON.stringify(st)).reason,"invalid_save");st.memories[0].id="photo-safe-1";st.memories[0].layout.f19.actionStage="bad";assert.equal(m.restoreSave(JSON.stringify(st)).reason,"invalid_save");assert.equal(s.getItem(KEY),raw);});
test('audio/effects settings normalize and persist; representative project includes basic decoration once',()=>{const {m,win,s}=setup();m.sound(false);m.effects('low');assert.equal(makeModel(s,catalog).read().settings.sound,false);assert.equal(m.read().settings.effects,'low');win();const first=m.purchase('f05');assert.equal(first.gift,'d-coaster');const balance=m.read().balance;assert.ok(m.read().decorOwned['d-coaster']);assert.equal(m.purchase('f05').changed,false);assert.equal(m.read().balance,balance);assert.equal(m.effects('unknown').reason,'effects');});