'use strict';
(() => {
  const catalog=window.CafeCatalog,model=window.CafeModel.makeModel(localStorage,catalog),fby=id=>model.byId(id),dby=id=>model.decorById(id),itemById=id=>fby(id)||dby(id);
  let state,storageError=null,tab='garden',zone='all',selected='f05',edit=null,placement=null,open=true,saveQueue=Promise.resolve(),scene=null,viewOnly=false,viewFocus=null,collectionView='cats';
  try{state=model.read();}catch(e){storageError=e.message;}
  const root=document.createElement('main');root.id='coffee-game';
  root.innerHTML=`<header class="game-header"><div><span class="game-kicker">작은 고양이들의 커피 정원</span><h1>고양이와 커피</h1></div><div class="wallet"><span>커피 방울</span><strong id="game-balance">0</strong></div><button id="game-puzzle" class="primary">퍼즐 하러 가기</button></header><nav class="game-tabs" aria-label="카페 메뉴"><button data-tab="garden">정원</button><button data-tab="build">시설</button><button data-tab="decor">꾸미기</button><button data-tab="cats">고양이</button><button data-tab="stories">이야기</button><button data-tab="album">추억</button><button data-tab="settings">설정</button></nav><section id="game-project"></section><p id="game-message" role="status" aria-live="polite"></p><section id="game-content"></section><footer class="game-footer"><span>시설·고양이 동작은 임시 표현입니다. 시설별 원본 시트로 교체할 수 있어요.</span><span>로컬 저장 · 실제 포인트와 연결되지 않아요</span></footer>`;
  const viewExit=document.createElement('button');viewExit.id='view-exit';viewExit.textContent='감상 마치기';viewExit.hidden=true;root.append(viewExit);viewExit.onclick=()=>{viewOnly=false;viewFocus=null;render();};document.body.append(root);
  const nav=document.createElement('div');nav.id='return-cafe';nav.innerHTML='<button>카페로 돌아가기 <span id="puzzle-wallet"></span></button>';nav.hidden=true;const easy=document.createElement('button');easy.id='easy-puzzle';easy.textContent='쉬운 퍼즐 새로 시작';easy.onclick=()=>window.__lumi?.openLevel(0);nav.append(easy);document.body.append(nav);
  const companionPanel=document.createElement('aside');companionPanel.id='puzzle-companion';companionPanel.hidden=true;document.body.append(companionPanel);
  const $=id=>document.getElementById(id),msg=t=>{$('game-message').textContent=t;if($('detail-message'))$('detail-message').textContent=t;};
  function popup(text){msg(text);}
  function action(fn){const run=async()=>{if(storageError){msg(storageError);return {ok:false,reason:'storage'};}try{const result=await (navigator.locks?navigator.locks.request('cats-coffee-save',fn):fn());state=result.state||model.read();render();if(result.message)msg(result.message);return result;}catch(e){msg('저장할 수 없어요. 기존 저장을 보존했습니다. '+e.message);return {ok:false,reason:'storage'};}};saveQueue=saveQueue.then(run,run);return saveQueue;}
  function allOwned(){return state?Object.entries(state.owned):[];}
  function layout(){return edit?edit.layout:Object.fromEntries(allOwned().map(([id,o])=>[id,o.position]));}
  function show(opened){open=opened;root.hidden=!open;nav.hidden=open;companionPanel.hidden=open;if(!open&&state){const f=catalog.facilities.find(f=>f.catId===state.companion),target=fby(state.project);companionPanel.innerHTML=window.CafeArt.html(f,state.owned[f.id].level)+'<div><strong>'+f.catName+'와 함께</strong><span>'+(target?target.name+' 프로젝트':'편안한 퍼즐 시간')+'</span><small>망치로 한 칸 도와줄게요</small></div>';}document.body.classList.toggle('cafe-visible',open);if(open){try{state=model.read();}catch(e){storageError=e.message;}render();}else document.getElementById('c')?.focus();}
  function project(){
    if(!state)return '';
    const f=fby(state.project);if(!f)return '<div class="project-card"><span>마음에 드는 다음 고양이 장면을 골라보세요.</span><button data-go="build">시설 둘러보기</button></div>';
    const o=state.owned[f.id],max=o?.level===3,cost=o?(max?0:f.upgrades[o.level-1]):f.price;
    return `<div class="project-card"><div><span class="project-label">다음에 보고 싶은 장면</span><strong>${f.catName}의 ${f.name}${o?' · 다음 행동':''}</strong><span class="project-action">${o?f.variation:f.action}</span></div><div class="project-progress"><span>${max?'모든 행동이 열렸어요':Math.max(0,cost-state.balance)+' 커피 방울 더 모으면 돼요'}</span><progress max="${cost||1}" value="${Math.min(state.balance,cost||1)}"></progress><button data-detail="${f.id}">${max?'장면 보기':'프로젝트 보기'}</button></div></div>`;
  }
  function render(){
    if(!state){$('game-content').innerHTML='<div class="empty-state"><h2>저장 확인이 필요해요</h2><p></p></div>';$('game-content').querySelector('p').textContent=storageError;$('game-content').insertAdjacentHTML('beforeend',recovery());bindRecovery();return;}
    const oldScroll=$('garden-world')?.parentElement;const oldLeft=oldScroll?.scrollLeft||0,oldTop=oldScroll?.scrollTop||0;root.classList.toggle('viewing',viewOnly);viewExit.hidden=!viewOnly;
    $('game-balance').textContent=state.balance;$('puzzle-wallet').textContent=state.balance;$('game-project').innerHTML=project();
    document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false'));
    $('game-content').innerHTML=tab==='garden'?garden():tab==='build'?build():tab==='decor'?decorate():tab==='cats'?cats():tab==='stories'?stories():tab==='album'?album():settings();
    root.dataset.lighting=state.settings.lighting;root.dataset.floor=state.surfaces.floor||'';root.dataset.path=state.surfaces.path||'';root.style.setProperty('--garden-extra',(state.chapter-1)*120+'px');root.style.setProperty('--garden-height-extra',(state.chapter-1)*65+'px');root.dataset.gardenSize=Object.values(state.owned).filter(o=>o.position).length>6?'spacious':'cozy';
    root.dataset.effects=state.settings.effects;root.classList.toggle('reduced-motion',state.settings.reduceMotion);companionPanel.classList.toggle('reduced-motion',state.settings.reduceMotion);
    bind();
    const newScroll=$('garden-world')?.parentElement;if(newScroll){newScroll.scrollLeft=oldLeft;newScroll.scrollTop=oldTop;}
    root.querySelectorAll('[data-station]').forEach(n=>window.CafeArt.mountAtlas(n.querySelector('.facility-art'),fby(n.dataset.station),state.owned[n.dataset.station].actionStage||state.owned[n.dataset.station].level));
  }
  function garden(){
    const positions=layout(),active=Object.entries(positions).filter(([,p])=>p!==null),stored=Object.entries(positions).filter(([,p])=>p===null);
    return `<div class="garden-toolbar"><div><h2>나의 커피 정원</h2><p>${catalog.chapters[state.chapter-1].name} · ${allOwned().length}마리 입주</p></div>${edit?'<div><button id="edit-undo">되돌리기</button><button id="edit-cancel">취소</button><button id="edit-save" class="primary">배치 저장</button></div>':'<div><button id="view-garden">감상</button><button id="edit-start">배치 편집</button></div>'}</div>${edit?`<p class="edit-instruction">${placement?itemById(placement).name+'을 놓을 위치를 눌러주세요.':'시설을 고른 뒤 다른 위치를 누르거나 보관하세요.'}</p>`:''}<div class="garden-scroll" tabindex="0" aria-label="가로로 움직일 수 있는 커피 정원"><div id="garden-world" class="garden-world ${edit?'editing':''}"><div class="garden-path"></div>${catalog.zones.map(z=>`<div class="zone-ground zone-${z.id} ${z.id+1>state.chapter?'terrain-preview':''}"><span>${z.id+1>state.chapter?'다음 분위기 · ':''}${z.name}</span></div>`).join('')}${decorGarden()}${guestGarden()}${active.map(([id,p])=>{const f=fby(id),o=state.owned[id];return `<button class="station ${placement===id?'selected':''} ${viewFocus===id?'view-focus':''}" data-station="${id}" style="left:${p.x}%;top:${p.y}%" aria-label="${f.name}, ${f.catName}, ${o.level}단계">${window.CafeArt.html(f,o.actionStage||o.level)}<span class="station-name">${f.name}</span><span class="cat-label">${f.catName}${o.level>1?' · '+o.level+'단계':''}</span></button>`;}).join('')}</div></div>${edit?`<div class="storage-strip"><strong>보관함</strong>${stored.map(([id])=>`<button data-place="${id}">${fby(id).name}</button>`).join('')||'<span>보관 중인 시설이 없어요</span>'}${Object.entries(edit.decor).filter(([id,p])=>p===null&&!['floor','path'].includes(dby(id)?.kind)).map(([id])=>`<button data-place="${id}">${dby(id).name}</button>`).join('')}${placement?`<button id="store-selected">${itemById(placement).name} 보관</button>`:''}</div>`:''}${active.length<=1?'<div class="garden-hint"><strong>첫 핸드드립 바를 열어보세요</strong><p>퍼즐 첫 클리어로 100개를 모으면 방울이가 입주해요. 이미 깬 퍼즐도 다시 플레이할 수 있어요.</p></div>':''}<div id="facility-detail"></div>`;
  }
  function build(){return `<div class="section-heading"><h2>다음 장면을 골라보세요</h2><span>36개 시설 · 6개 구역</span></div>${terrainProgress()}<div class="zone-filters"><button data-zone="all" aria-pressed="${zone==='all'}">전체</button>${catalog.zones.map(z=>`<button data-zone="${z.id}" aria-pressed="${zone===String(z.id)}">${z.name}</button>`).join('')}</div><div class="catalog-grid">${catalog.facilities.filter(f=>zone==='all'||String(f.zone)===zone).map(f=>{const o=state.owned[f.id],locked=f.chapter>state.chapter&&!o;return `<button class="catalog-card ${locked?'locked':''}" data-detail="${f.id}">${window.CafeArt.html(f,o?.level||1)}<strong>${f.name}</strong><span>${f.catName} · ${catalog.zones[f.zone].name}</span><small>${o?'입주 · '+o.level+'단계':locked?f.chapter+'장 프로젝트로 해금':f.price+' 커피 방울'}</small></button>`;}).join('')}</div><div id="facility-detail"></div>`;}
  function cats(){return `<div class="collection-switch">${[['cats','고양이'],['facilities','시설'],['menus','메뉴']].map(([id,name])=>`<button data-collection="${id}" aria-pressed="${collectionView===id}">${name}</button>`).join('')}</div><div class="section-heading"><h2>고양이들의 작은 일상</h2><span>${allOwned().length} / 36 입주</span></div><div class="catalog-grid">${(collectionView==='menus'?catalog.facilities.filter(f=>[4,5,6,7,8,9,10,11,12,14,15,16,17].includes(f.number)):catalog.facilities).map(f=>{const o=state.owned[f.id];return `<button class="catalog-card ${o?'':'locked'}" data-detail="${f.id}">${window.CafeArt.html(f,o?.level||1)}<strong>${o?f.catName:'아직 만나지 않은 고양이'}</strong><span>${collectionView==='menus'?f.result:f.name}</span><small>${o?(o.position?'정원에서 지내는 중':'보관함에서 쉬는 중'):'시설을 열면 함께 입주해요'}</small>${state.companionRecords[f.catId]?`<small>함께 ${state.companionRecords[f.catId].runs}판 · ${state.companionRecords[f.catId].wins}번 클리어</small>`:''}${state.companion===f.catId?'<em>오늘의 동행</em>':''}</button>`;}).join('')}</div><div id="facility-detail"></div>`;}
  function stories(){const o=state.order;return `<div class="section-heading"><h2>한 잔에 담긴 작은 이야기</h2><span>시간 제한 없이 · 익숙한 퍼즐로 준비</span></div>${o?`<div class="story-current"><strong>${fby(o.facility).story.title} · ${o.completed}/2</strong><p>${o.served?'손님이 이용을 마쳤어요. 감사 장면은 추억에서 다시 볼 수 있어요.':o.completed===2?'준비 완료! 시설을 배치하고 손님을 맞이해주세요.':fby(o.facility).story.request}</p><button id="play-order">새 주문 퍼즐 시작</button>${o.completed===2&&!o.served?'<button id="serve-order" class="primary">손님 맞이하기</button>':''}</div>`:''}<div id="story-scene">${scene?storyScene(scene.id,scene.phase):''}</div><div class="catalog-grid">${allOwned().map(([id,item])=>{const f=fby(id),progress=state.orderBook[id];return `<button class="catalog-card" data-order="${id}">${window.CafeArt.html(f,item.actionStage||item.level)}<strong>${f.story.title}</strong><span>${f.story.guest}</span><small>${progress?.served?'이용 완료 · 다시 보기':progress?progress.completed+'/2 준비':'주문 이야기 열기'}</small></button>`;}).join('')}</div>`;}
  function album(){const photos=state.memories.filter(m=>m.kind==='photo'),events=state.memories.filter(m=>m.kind!=='photo');return `<div class="section-heading"><h2>우리 카페의 추억</h2><button id="remember-garden">현재 정원 기억하기</button></div>${!state.memories.length?'<div class="empty-state"><p>입주와 성장, 손님 이야기를 마치면 이곳에 추억이 남아요.</p></div>':''}<div class="catalog-grid">${events.map(m=>{const f=fby(m.facility);return `<button class="catalog-card" data-${m.kind==='story'||m.kind==='visit'?'story':'detail'}="${f.id}">${window.CafeArt.html(f,state.owned[f.id]?.level||1)}<strong>${f.catName}${m.kind==='arrival'?'의 입주':m.kind==='growth'?'의 새로운 행동':m.kind==='visit'?'의 손님 감사 인사':m.kind==='companion'?'의 첫 퍼즐 산책':'의 첫 손님'}</strong><span>${m.kind==='story'?'따뜻한 한 잔을 준비하고, 손님에게 작은 인사를 건넸어요.':f.result}</span><small>장면 다시 보기</small></button>`;}).join('')}${photos.map((m,i)=>`<button class="catalog-card" data-memory="${m.id}"><strong>정원 기억 ${i+1}</strong><span>${Object.keys(m.layout).length}마리와 함께</span><small>배치 기록 보기</small></button>`).join('')}</div><div id="memory-scene"></div><div id="facility-detail"></div>`;}
  function settings(){return `<div class="settings-card"><h2>편안한 커피 시간</h2><label><input type="checkbox" id="reduce-motion" ${state.settings.reduceMotion?'checked':''}> 움직임 줄이기</label><label><input type="checkbox" id="sound-enabled" ${state.settings.sound?'checked':''}> 퍼즐 소리</label><label>효과 강도 <select id="effect-strength"><option value="full" ${state.settings.effects==='full'?'selected':''}>기본</option><option value="low" ${state.settings.effects==='low'?'selected':''}>부드럽게</option></select></label><label>정원의 조명 <select id="garden-lighting">${[['day','햇살'],['sunset','노을'],['night','밤']].map(([id,name])=>`<option value="${id}" ${state.settings.lighting===id?'selected':''}>${name}</option>`).join('')}</select></label><p>게임 진행은 이 브라우저에 저장돼요. 구매, 성장, 배치와 고양이 기록을 함께 보존합니다.</p><p>기본 시설은 대표 프로젝트를 완성하며 차례로 열립니다. 모든 시설을 최고 단계로 올릴 필요는 없어요.</p><p>첫 클리어 ${catalog.rewardFirst} · 반복 클리어 ${catalog.rewardRepeat} 커피 방울. 시설 탭이나 대기 시간에는 재화를 지급하지 않아요.</p><p class="asset-note">현재 시설과 고양이는 동작·배치를 검증하는 임시 벡터 표현입니다. 원본 시설별 스프라이트 제작은 진행하지 않았어요.</p>${recovery()}</div>`;}
  function terrainProgress(){const current=catalog.chapters[state.chapter-1],representative=fby(current.representative);return `<article class="terrain-progress"><strong>${state.chapter}/6 정원 확장</strong><p>${state.chapter===6?'모든 기본 빈터가 열렸어요. 취향대로 시설과 소품을 배치해주세요.':representative.name+'를 완성하면 다음 빈터가 넓어져요. 모든 시설의 최고 성장을 기다릴 필요는 없어요.'}</p>${state.chapter<6?`<button data-detail="${representative.id}">대표 프로젝트 보기</button>`:''}</article>`;}
  function decoMarkup(id){const d=dby(id);return `<span class="decor-shape decor-${d.kind}" aria-hidden="true"></span><span>${d.name}</span>`;}
  function decorGarden(){const positions=edit?edit.decor:Object.fromEntries(Object.entries(state.decorOwned).map(([id,o])=>[id,o.position]));return Object.entries(positions).filter(([,p])=>p!==null).map(([id,p])=>`<button class="garden-decor ${placement===id?'selected':''}" data-deco="${id}" style="left:${p.x}%;top:${p.y}%" aria-label="${dby(id).name}">${decoMarkup(id)}</button>`).join('');}
  function guestGarden(){const o=state.order;if(!o||!state.owned[o.facility]?.position)return '';const p=state.owned[o.facility].position,f=fby(o.facility);return `<div class="garden-guest ${o.served?'guest-use':''}" style="left:${p.x}%;top:${p.y}%" aria-label="손님 이용 상태"><span>${f.story.guest}</span><small>${o.served?'고마워요!':o.completed===2?'주문을 기다려요':'준비를 지켜봐요'}</small></div>`;}
  function decorate(){return `<div class="section-heading"><h2>우리 정원 꾸미기</h2><span>시설과 별도로 보관하는 19종 소품</span></div><p class="asset-note">소품 그림은 위치 확인용 임시 표시입니다.</p><div class="catalog-grid">${catalog.decorations.map(d=>{const owned=state.decorOwned[d.id],surface=['floor','path'].includes(d.kind);return `<article class="catalog-card deco-card">${decoMarkup(d.id)}<strong>${d.category}</strong><small>${owned?(surface?(state.surfaces[d.kind]===d.id?'선택 중':'보유'):(owned.position?'배치 중':'보관 중')):d.price+' 커피 방울'}</small>${owned?`<button data-${surface?'surface':'decor-place'}="${d.id}">${surface?'선택':'배치 / 보관'}</button>`:`<button data-decor-buy="${d.id}">구매</button>`}</article>`;}).join('')}</div>`;}
  function recovery(){return `<section class="save-tools"><h3>내 저장 보관·복원</h3><p>복원 전에 현재 내용을 별도로 보존하며, 형식과 잔액이 맞는 저장만 적용합니다.</p><button id="restore-backup">이전 저장 복원</button><button id="export-save">저장 내용 보기</button><label>보관한 저장 붙여넣기<textarea id="save-import" aria-label="복원할 저장 내용"></textarea></label><button id="restore-import">확인 후 복원</button><textarea id="save-export" readonly hidden aria-label="보관할 저장 내용"></textarea><p id="save-status" role="status"></p></section>`;}
  function bindRecovery(){if(!$('restore-backup'))return;const recover=async fn=>{try{const r=await (navigator.locks?navigator.locks.request('cats-coffee-save',fn):fn());if(r.ok){state=r.state;storageError=null;edit=null;placement=null;render();popup('검증된 저장을 복원했어요.');}else $('save-status').textContent=r.message;}catch(e){$('save-status').textContent='복원하지 못했어요. 현재 저장을 보존했습니다. '+e.message;}};$('restore-backup').onclick=()=>recover(()=>model.restoreBackup());$('restore-import').onclick=()=>{const raw=$('save-import').value;recover(()=>model.restoreSave(raw));};$('export-save').onclick=()=>{const raw=localStorage.getItem(model.key);$('save-export').hidden=false;$('save-export').value=raw||JSON.stringify(model.read());};}
  function storyScene(id,phase=0){scene={id,phase};const f=fby(id),o=state.order?.facility===id?state.order:state.orderBook[id],steps=[f.story.request,f.story.preparing,f.story.served,f.story.thanks];return `<article class="story-scene"><h3>${f.story.title}</h3><span class="guest-name">${f.story.guest}</span><div class="story-stage">${window.CafeArt.html(f,state.owned[id].actionStage||state.owned[id].level)}<div><strong>${f.story.stages[phase]}</strong><p>${steps[phase]}</p></div></div><ol>${f.story.stages.map((x,i)=>`<li ${i===phase?'aria-current="step"':''}>${x}</li>`).join('')}</ol>${phase<3?`<button id="story-next" ${phase===1&&(!o||o.completed<2)?'disabled':''}>${phase===1&&(!o||o.completed<2)?'퍼즐 두 판을 준비해주세요':'다음 장면'}</button>`:'<button id="story-restart">다시 보기</button>'}<p class="asset-note">시설별 이야기와 이용 단계이며, 고유 손님 애니메이션 원본은 대기 중입니다.</p></article>`;}
  function detail(id){
    selected=id;const f=fby(id),o=state.owned[id],locked=f.chapter>state.chapter&&!o;
    if(!$('facility-detail')){tab='build';render();}
    $('facility-detail').innerHTML=`<div class="detail-scrim"><article class="detail-card" aria-label="시설 상세"><button id="detail-close" class="close-button" aria-label="상세 닫기">×</button>${window.CafeArt.html(f,o?.actionStage||o?.level||1)}<span class="detail-zone">${catalog.zones[f.zone].name} · ${f.chapter}장</span><h2>${f.name}</h2><h3>${f.catName}${o?' · '+o.level+'단계':''}</h3><p>${f.personality}</p><dl><dt>기본 작업</dt><dd>${f.action}</dd><dt>${o?.level>=2?'열린 코믹 행동':'다음 성장에서 볼 행동'}</dt><dd>${f.variation}</dd><dt>눈에 보이는 결과</dt><dd>${f.result}</dd></dl><div class="detail-actions"><button id="set-project">다음 목표로 선택</button>${o?`<label class="behavior-choice">행동 보기 <select id="behavior-stage">${Array.from({length:o.level},(_,i)=>`<option value="${i+1}" ${(o.actionStage||o.level)===i+1?'selected':''}>${i+1}단계 ${i?'성장 행동':'기본 행동'}</option>`).join('')}</select></label>${o.level<3?`<button id="upgrade-facility" class="primary">행동 성장 · ${f.upgrades[o.level-1]}</button>`:'<span>모든 성장 단계 완료</span>'}<button id="place-facility">${o.position?'이동 / 보관':'정원에 배치'}</button><button id="set-companion">동행으로 선택</button>`:locked?'<span>앞 장 대표 프로젝트를 완성하면 열려요</span>':`<button id="buy-facility" class="primary">${f.catName} 입주 · ${f.price}</button>`}</div><p class="asset-note">시설 전용 애니메이션 원본 대기 · 현재는 동작 가안</p></article></div>`;
    const status=document.createElement('p');status.id='detail-message';status.setAttribute('role','status');status.textContent=$('game-message').textContent;$('facility-detail').querySelector('.detail-card').append(status);
    $('detail-close').onclick=()=>{$('facility-detail').replaceChildren();};
    $('set-project').onclick=async()=>{await action(()=>model.setProject(id));popup(f.catName+'의 장면을 다음 목표로 골랐어요.');detail(id);};
    if($('buy-facility'))$('buy-facility').onclick=async()=>{const r=await action(()=>model.purchase(id));if(r.ok){tab='garden';startEdit(id);popup(f.catName+'이 입주했어요. 정원에서 자리를 골라주세요.');}else detail(id);};
    if($('upgrade-facility'))$('upgrade-facility').onclick=async()=>{const r=await action(()=>model.upgrade(id));detail(id);if(r.ok)popup(f.catName+'의 새로운 행동과 공간 장식이 열렸어요.');};
    if($('behavior-stage'))$('behavior-stage').onchange=async e=>{await action(()=>model.behavior(id,Number(e.target.value)));detail(id);};
    if($('place-facility'))$('place-facility').onclick=()=>{tab='garden';startEdit(id);};
    if($('set-companion'))$('set-companion').onclick=async()=>{await action(()=>model.setCompanion(f.catId));detail(id);popup(f.catName+'과 퍼즐에 함께 갈 거예요. 도움 성능은 원본 퍼즐의 공통 망치예요.');};
  }
  function startEdit(id=null){edit={revision:state.revision,layout:Object.fromEntries(allOwned().map(([key,o])=>[key,o.position?{...o.position}:null])),decor:Object.fromEntries(Object.entries(state.decorOwned).map(([key,o])=>[key,o.position?{...o.position}:null])),history:[]};placement=id;render();}
  function rememberEdit(){edit.history.push(JSON.parse(JSON.stringify({layout:edit.layout,decor:edit.decor})));}
  function bind(){
    bindRecovery();
    root.querySelectorAll('[data-collection]').forEach(b=>b.onclick=()=>{collectionView=b.dataset.collection;render();});
    root.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>{scene={id:b.dataset.story,phase:3};tab='stories';render();});
    root.querySelectorAll('[data-decor-buy]').forEach(b=>b.onclick=()=>action(()=>model.purchaseDecoration(b.dataset.decorBuy)));
    root.querySelectorAll('[data-surface]').forEach(b=>b.onclick=()=>action(()=>model.equipSurface(b.dataset.surface)));
    root.querySelectorAll('[data-decor-place]').forEach(b=>b.onclick=()=>{tab='garden';startEdit(b.dataset.decorPlace);});
    root.querySelectorAll('[data-deco]').forEach(b=>b.onclick=e=>{e.stopPropagation();if(edit){placement=b.dataset.deco;render();}else popup(dby(b.dataset.deco).name+' · 배치 편집에서 옮길 수 있어요.');});
    if($('story-next'))$('story-next').onclick=()=>{scene.phase=Math.min(3,scene.phase+1);render();};
    if($('story-restart'))$('story-restart').onclick=()=>{scene.phase=0;render();};
    if($('play-order'))$('play-order').onclick=()=>{const target=fby(state.order.facility),unlocked=window.__lumi.progress().unlocked,index=Math.max(0,Math.min(target.chapter,unlocked)-1);show(false);window.__lumi.openLevel(index);};
    if($('serve-order'))$('serve-order').onclick=async()=>{const r=await action(()=>model.serveOrder());if(r.ok){scene={id:state.order.facility,phase:3};render();popup('손님이 이용하고 감사 인사를 전했어요.');}};
    root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{tab=b.dataset.go;render();});
    root.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));
    root.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{zone=b.dataset.zone;render();});
    root.querySelectorAll('[data-station]').forEach(b=>b.onclick=e=>{e.stopPropagation();if(viewOnly){viewFocus=viewFocus===b.dataset.station?null:b.dataset.station;render();}else if(edit){placement=b.dataset.station;render();}else{b.classList.add('cat-greet');detail(b.dataset.station);}});
    root.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>{placement=b.dataset.place;render();});
    if($('view-garden'))$('view-garden').onclick=()=>{viewOnly=true;viewFocus=null;render();};
    if($('edit-undo')){$('edit-undo').disabled=edit.history.length===0;$('edit-undo').onclick=()=>{const previous=edit.history.pop();edit.layout=previous.layout;edit.decor=previous.decor;placement=null;render();};}
    if($('edit-start'))$('edit-start').onclick=()=>startEdit();
    if($('edit-cancel'))$('edit-cancel').onclick=()=>{edit=null;placement=null;render();popup('편집을 취소하고 이전 배치로 돌아왔어요.');};
    if($('edit-save'))$('edit-save').onclick=async()=>{const r=await action(()=>model.saveLayout(edit.layout,edit.revision,edit.decor));if(r.ok){edit=null;placement=null;render();popup('배치가 저장됐어요.');}};
    if($('store-selected'))$('store-selected').onclick=()=>{rememberEdit();(dby(placement)?edit.decor:edit.layout)[placement]=null;placement=null;render();};
    if($('garden-world'))$('garden-world').onclick=e=>{if(!edit||!placement)return;rememberEdit();const r=e.currentTarget.getBoundingClientRect();(dby(placement)?edit.decor:edit.layout)[placement]={x:Math.round((e.clientX-r.left)/r.width*100),y:Math.round((e.clientY-r.top)/r.height*100)};placement=null;render();};
    if($('sound-enabled'))$('sound-enabled').onchange=async e=>{const r=await action(()=>model.sound(e.target.checked));if(r.ok)window.__lumi?.setMuted(!r.state.settings.sound);};
    if($('effect-strength'))$('effect-strength').onchange=e=>action(()=>model.effects(e.target.value));
    if($('reduce-motion'))$('reduce-motion').onchange=e=>action(()=>model.setting(e.target.checked));
    if($('garden-lighting'))$('garden-lighting').onchange=e=>action(()=>model.lighting(e.target.value));
    root.querySelectorAll('[data-order]').forEach(b=>b.onclick=async()=>{const id=b.dataset.order;const r=await action(()=>model.beginOrder(id));if(r.ok){scene={id,phase:state.order.completed===2?2:0};render();}if(r.ok)popup(r.reason==='complete'?'이 이야기는 이미 추억에 남아 있어요.':'이 주문은 어느 퍼즐을 클리어해도 진행돼요.');});
    if($('remember-garden'))$('remember-garden').onclick=()=>action(()=>model.remember('photo:'+crypto.randomUUID()));
    root.querySelectorAll('[data-memory]').forEach(b=>b.onclick=()=>{const m=state.memories.find(x=>x.id===b.dataset.memory);$('memory-scene').innerHTML=`<div class="memory-card"><h3>이때의 우리 정원</h3><p>배치를 바꾸지 않고 당시 기록을 감상합니다.</p><div class="memory-mini" data-lighting="${m.lighting}" data-floor="${m.surfaces?.floor||''}" data-path="${m.surfaces?.path||''}">${Object.entries(m.layout).filter(([,o])=>o.position).map(([id,o])=>`<div class="memory-station" style="left:${o.position.x}%;top:${o.position.y}%">${window.CafeArt.html(fby(id),o.actionStage||o.level)}</div>`).join('')}${Object.entries(m.decor||{}).filter(([,o])=>o.position).map(([id,o])=>`<div class="memory-decor" style="left:${o.position.x}%;top:${o.position.y}%">${decoMarkup(id)}</div>`).join('')}</div></div>`;});
  }
  root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(edit){popup('먼저 배치 저장 또는 취소를 눌러주세요.');return;}tab=b.dataset.tab;root.scrollTop=0;render();});
  $('game-puzzle').onclick=()=>{if(storageError){popup('저장을 복원한 뒤 퍼즐을 시작해주세요.');return;}if(edit){popup('퍼즐로 가기 전에 배치를 저장하거나 취소해 주세요.');return;}show(false);};
  nav.querySelector('button').onclick=()=>show(true);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&open){if(viewOnly){viewOnly=false;viewFocus=null;render();}else if($('facility-detail')?.children.length){$('facility-detail').replaceChildren();}else if(edit){edit=null;placement=null;render();popup('편집을 취소했어요.');}}});
  window.addEventListener('storage',e=>{if(e.key===model.key){try{state=model.read();if(edit)popup('다른 창에서 저장이 바뀌었어요. 편집을 취소하고 다시 열어주세요.');else render();}catch(err){storageError=err.message;popup(storageError);}}});
  window.catCafe={
    isOpen:()=>open,
    beginAttempt:level=>{const id=crypto.randomUUID();return action(()=>model.beginAttempt(level,id)).then(r=>r.ok?id:null);},
    finishAttempt:(id,won)=>action(()=>model.finishAttempt(id,won)).then(r=>{if(r.amount)popup(`퍼즐 클리어! 커피 방울 ${r.amount}개가 정원에 모였어요.`);return r;}),
    abandon:id=>action(()=>model.abandon(id)),
    assist:()=>{companionPanel.classList.remove('companion-assist');void companionPanel.offsetWidth;companionPanel.classList.add('companion-assist');},
    settings:()=>state?.settings||{sound:true,effects:'full',reduceMotion:false},
    soundChanged:value=>action(()=>model.sound(value)).then(r=>{if(!r.ok)window.__lumi?.setMuted(!state?.settings.sound);}),
    snapshot:()=>model.read(),open:()=>show(true),close:()=>show(false),storageKey:model.key,
    project:()=>state?.project?fby(state.project):null,
    companion:()=>state?catalog.facilities.find(f=>f.catId===state.companion):null,
    // Fixture access for isolated local QA, no server or external rewards.
    qa:{model,select:id=>detail(id),startEdit,idToFacility:fby}
  };
  show(true);
})();
